# Generated by Django 3.0.9 on 2020-08-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='raing',
            new_name='rating',
        ),
    ]
